Controllers/PermissionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjPermManage.constants;
using ProjPermManage.Helpers;
using ProjPermManage.Models;
using ProjPermManage.Seeds;

namespace ProjPermManage.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class PermissionController : Controller
    {

        private readonly RoleManager<IdentityRole> roleManager;

        public PermissionController(RoleManager<IdentityRole> roleManager)
        {
            this.roleManager = roleManager;
        }

        public async Task<IActionResult> Index(string roleId)
        {
            var model = new PermissionViewModel();
            var allPermissions = new List<RoleClaimsViewModel>();
            allPermissions.GetPermissions(typeof(Permissions.Products), roleId);
            var role = await roleManager.FindByIdAsync(roleId);
            model.RoleId = roleId;
            var Claim = await roleManager.GetClaimsAsync(role);
            var allClaimValues = allPermissions.Select(a => a.Value).ToList();
            var roleClaimValues = Claim.Select(a => a.Value).ToList();
            var authorizedClaims = allClaimValues.Intersect(roleClaimValues).ToList();

            foreach (var permission in allPermissions)
            {
                if (authorizedClaims.Any(a => a == permission.Value))
                {
                    permission.Selected = true;
                }
            }
            model.RoleClaims = allPermissions;
            return View(model);
        }


        public async Task<IActionResult> Update(PermissionViewModel model)
        {
            var role = await roleManager.FindByIdAsync(model.RoleId);
            var claims = await roleManager.GetClaimsAsync(role);

            foreach (var claim in claims)
            {
                await roleManager.RemoveClaimAsync(role, claim);
            }

            var selectedClaims = model.RoleClaims.Where(a => a.Selected).ToList();

            foreach (var claim in selectedClaims)
            {
                await roleManager.AddAPermissionClaim(role, claim.Value);
            }

            return RedirectToAction("Index", new { roleId = model.RoleId });
        }
    }
}

Controllers/RolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MySqlX.XDevAPI.Common;
using ProjPermManage.constants;
using ProjPermManage.Data;

namespace ProjPermManage.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class RolesController : Controller
    {
        private readonly RoleManager<IdentityRole> roleManager;
        private readonly UserManager<IdentityUser> userManager;

        public RolesController(RoleManager<IdentityRole> roleManager, UserManager<IdentityUser> userManager)
        {
            this.roleManager = roleManager;
            this.userManager = userManager;
        }


        public async Task<IActionResult> Index()
        {
            var roles = await roleManager.Roles.ToListAsync();
            return View(roles);
        }

        [HttpPost]
        public async Task<IActionResult> AddRole(string roleName)
        {
            if (roleName != null)
            {
                await roleManager.CreateAsync(new IdentityRole(roleName.Trim()));
            }

            return RedirectToAction("Index");
        }


        public async Task<IActionResult> DeleteRole(string Id)
        {
            if (Id != null)
            {
                //je recupère l'utilisateur
                var role = await roleManager.FindByIdAsync(Id);

                if (role == null)
                {
                    ViewBag.ErrorMessage = $"Role with id = {Id} can not found";
                    return View("Index");
                }
                else
                {
                    var result = await roleManager.DeleteAsync(role);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return RedirectToAction("Index");
                }

            }
            return View();

        }
    }
}

Views/Roles/Index.cshtml
@using Microsoft.AspNetCore.Identity
@model IEnumerable<IdentityRole>


@{ ViewData["Title"] = "Index"; }

<h1>List Of Roles</h1>
<br />

<form method="post" asp-action="addrole" asp-controller="roles">
    <div class="input-group">
        <input name="roleName" class="form-control w-25 mr-3 mb-2" />
        <span class="input-group-btn mb-2">
            <button class="btn btn-info">Add A New Role</button>
        </span>
    </div>
</form>
<table class="table table-striped" id="roleTable">
    <thead>
        <tr>
            <th>Role</th>
            <th>Id</th>
            <th style="width:10%">Action Role</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var role in Model)
        {
            <div class="row">
                <div id="id01" class="col-md-6 col-sm-12 modal rounded shadow p-3 mb-5">
                    <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Information Delete">&times;</span>
                    <form class="modal-content" method="post" asp-action="DeleteRole" asp-controller="roles" asp-route-Id="@role.Id">
                        <h1 class="text-center h4 mt-3">Delete Role</h1>
                        <p>Are you sure you want to delete this role?</p>

                        <div class="clearfix row">
                            <button asp-action="Index" asp-controller="roles" class="btn btn-sm btn-dark form-control mr-2 ml-2 mb-2">Cancel</button>
                            <button type="submit" class="btn btn-sm btn-danger form-control mr-2 ml-2">Delete</button>
                        </div>
                    </form>
                </div>
            </div>
            <tr>
                <td>
                    @role.Name
                </td>
                <td>
                    @role.Id
                </td>
                <td class="text-right">
                    <div class="btn-group">
                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Action
                        </button>
                        <div class="dropdown-menu shadow animated--grow-in">

                            <a class="dropdown-item" @*asp-action="Update" asp-controller="Permission"*@>
                                <i class="fas fa-pencil-alt"></i>
                                Edit
                            </a>
                            <a class="dropdown-item" onclick="document.getElementById('id01').style.display='block'">
                                <i class="fas fa-trash-alt"></i>
                                Delete
                            </a>

                            @if (role.Name != "SuperAdmin")
                            {
                                <a style="margin-right:10px" asp-controller="Permission" asp-action="Index" asp-route-roleId="@role.Id" class="dropdown-item">
                                    <i class="fas fa-wrench"></i>
                                    Manage Permissions
                                </a>
                            }

                        </div>
                    </div>
                </td>
            </tr>
        }
    </tbody>
</table>

@section Scripts {

    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}