Models/UserRolesViewModel.cs
using System;
using System.Collections.Generic;

namespace ProjPermManage.Models
{
    public class UserRolesViewModel
    {
        public string RoleId { get; set; }
        public string RoleName { get; set; }
        public bool Selected { get; set; }

    }

    public class ManagerUserRolesViewModel
    {
        public string UserId { get; set; }
        public IList<UserRolesViewModel> UserRoles { get; set; }
    }
}

Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using ProjPermManage.Models;

namespace ProjPermManage.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserController : Controller
    {
        private readonly UserManager<IdentityUser> userManager;

        public UserController(UserManager<IdentityUser> userManager)
        {
            this.userManager = userManager;
        }

        public async Task<IActionResult> Index()
        {
            var currentUser = await userManager.GetUserAsync(HttpContext.User);
            var allUsersExceptCurrentUser = await userManager.Users.Where(a => a.Id != currentUser.Id).ToListAsync();
            return View(allUsersExceptCurrentUser);
        }

        public async Task<IActionResult> DeleteUser(string Id)
        {
            if (Id != null)
            {
                //je recupère l'utilisateur
                var user = await userManager.FindByIdAsync(Id);

                if (user == null)
                {
                    ViewBag.ErrorMessage = $"User with id{Id} can not found";
                    return View();
                }
                else
                {
                    var result = await userManager.DeleteAsync(user);

                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }

                    foreach (var error in result.Errors)
                    {
                        ModelState.AddModelError("", error.Description);
                    }
                    return RedirectToAction("Index");
                }

            }
            return View();

        }

        [HttpGet]
        public async Task<IActionResult> UpdateUser(string Id)
        {
            var user = await userManager.FindByIdAsync(Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = $"user with id = {Id} connot found";
                return View("NotFound");
            }

            var userClaims = await userManager.GetClaimsAsync(user);
            var userRoles = await userManager.GetRolesAsync(user);

            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                Claims = userClaims.Select(c => c.Value).ToList(),
                Roles = userRoles.ToList()
            };

            return View(model);
        }

        [HttpPost]
        /**
         * Mis à jour des information de l'utilisateur 
         */
        public async Task<IActionResult> UpdateUser(EditUserViewModel model)
        {
            var user = await userManager.FindByIdAsync(model.Id);

            if (user == null)
            {
                ViewBag.ErrorMessage = "user with id connot found";
                return View("NotFound");
            }
            else
            {
                user.Email = model.Email;
                user.UserName = model.UserName;
                var result = await userManager.UpdateAsync(user);

                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                }
            }
           
            return View(model);
        }
    }
}

Controllers/UserRolesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ProjPermManage.Models;

namespace ProjPermManage.Controllers
{
    [Authorize(Roles = "SuperAdmin")]
    public class UserRolesController : Controller
    {
        private readonly SignInManager<IdentityUser> signInManager;
        private readonly UserManager<IdentityUser> userManager;
        private readonly RoleManager<IdentityRole> roleManager;

        public UserRolesController(SignInManager<IdentityUser> signInManager, UserManager<IdentityUser> userManager, RoleManager<IdentityRole> roleManager)
        {
            this.signInManager = signInManager;
            this.userManager = userManager;
            this.roleManager = roleManager;
        }

        [HttpGet]
        public async Task<IActionResult> Index(string userId)
        {
            var viewModel = new List<UserRolesViewModel>();

            var user = await userManager.FindByIdAsync(userId);

            foreach (var role in roleManager.Roles)
            {
                var userRolesViewModel = new UserRolesViewModel
                {
                    RoleName = role.Name,
                    RoleId = role.Id
                };

                if (await userManager.IsInRoleAsync(user, role.Name))
                {
                    userRolesViewModel.Selected = true;
                }
                else
                {
                    userRolesViewModel.Selected = false;
                }

                viewModel.Add(userRolesViewModel);
            }

            var model = new ManagerUserRolesViewModel()
            {
                UserId = userId,
                UserRoles = viewModel
            };

            return View(model);
        }

        /**
         * je recupère l'utilisateur ses roles et je les supprimes 
         * si le user n'existe pas j'affiche un message d'erreur
         * ensuite je lui ajoute ses nouveaux roles qui ont été sélectionnés
         */
        public async Task<IActionResult> Update(string userId, ManagerUserRolesViewModel model)
        {
            var user = await userManager.FindByIdAsync(userId);
            if (user == null)
            {
                ViewBag.ErrorMessage = $"User with Id= {user.Id} cannot be found";
                return View("Error");
            }
            var roles = await userManager.GetRolesAsync(user);
            var result = await userManager.RemoveFromRolesAsync(user, roles);

            if (!result.Succeeded)
            {
                ViewBag.ErrorMessage = $"User with Id= {user.Id} cannot be found";
                return View(model);
            }

            result = await userManager.AddToRolesAsync(user, model.UserRoles.Where(x => x.Selected).Select(y => y.RoleName));

            if (!result.Succeeded)
            {
                ModelState.AddModelError("", "Cannot add selected role to user");
                return View(model);
            }
            var currentUser = await userManager.GetUserAsync(User);
            await signInManager.RefreshSignInAsync(currentUser);
            await Seeds.DefaultUsers.SeedSuperAdminAsync(userManager, roleManager);
            return RedirectToAction("Index", new { UserId = userId });
        }
    }
}

Views/UserRoles/Index.cshtml
@model ProjPermManage.Models.ManagerUserRolesViewModel

@{ ViewData["Title"] = "Manage Roles"; }

<h3>Manage role for @Model.UserId</h3>

<br />
<div class="card">
    <div class="card-body table-responsive" id="viewAll">
        <form method="post" asp-controller="UserRoles" asp-action="Update" asp-route-id="@Model.UserId" class="d-inline">

            <input asp-for="@Model.UserId" type="hidden" />

            <table class="table table table-striped" id="userRolesTable">
                <thead>
                    <tr>
                        <th>Role</th>
                        <th>Status</th>
                    </tr>
                </thead>
                <tbody>
                    @for (int i = 0; i < Model.UserRoles.Count(); i++)
                    {
                        <tr>
                            <td>
                                <input asp-for="@Model.UserRoles[i].RoleName" type="hidden" />
                                @Model.UserRoles[i].RoleName
                            </td>
                            <td>
                                <div class="form-check m-1">
                                    <input asp-for="@Model.UserRoles[i].Selected" class="form-check-input" />
                                </div>
                            </td>
                        </tr>
                    }
                    <div asp-validation-summary="All" class="text-danger"></div>
                </tbody>
            </table>
            <div class="col-sm-12" style="padding:20px 20px 0px 0px">
                <button type="submit" id="save" class="btn bg-primary text-white">
                    <i class="fa fa-check"></i>
                    Save
                </button>
                <button asp-action="Index" asp-controller="User" id="save" class="btn btn-dark text-white">
                    <i class="fa fa-times-circle"></i>
                    Cancel
                </button>
            </div>
        </form>
    </div>
</div>












@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}